// Code generated by go-enum
// DO NOT EDIT!

package main

import (
	"fmt"
)

const (
	// MessageTypeError is a MessageType of type Error
	MessageTypeError MessageType = iota
	// MessageTypeRequest is a MessageType of type Request
	MessageTypeRequest
	// MessageTypeResponse is a MessageType of type Response
	MessageTypeResponse
	// MessageTypeEvent is a MessageType of type Event
	MessageTypeEvent
	// MessageTypeUnknown is a MessageType of type Unknown
	MessageTypeUnknown
)

const _MessageTypeName = "ErrorRequestResponseEventUnknown"

var _MessageTypeMap = map[MessageType]string{
	0: _MessageTypeName[0:5],
	1: _MessageTypeName[5:12],
	2: _MessageTypeName[12:20],
	3: _MessageTypeName[20:25],
	4: _MessageTypeName[25:32],
}

// String implements the Stringer interface.
func (x MessageType) String() string {
	if str, ok := _MessageTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("MessageType(%d)", x)
}

var _MessageTypeValue = map[string]MessageType{
	_MessageTypeName[0:5]:   0,
	_MessageTypeName[5:12]:  1,
	_MessageTypeName[12:20]: 2,
	_MessageTypeName[20:25]: 3,
	_MessageTypeName[25:32]: 4,
}

// ParseMessageType attempts to convert a string to a MessageType
func ParseMessageType(name string) (MessageType, error) {
	if x, ok := _MessageTypeValue[name]; ok {
		return x, nil
	}
	return MessageType(0), fmt.Errorf("%s is not a valid MessageType", name)
}

// MarshalText implements the text marshaller method
func (x MessageType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *MessageType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseMessageType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
